blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

# http://127.0.0.2:8080/blog/
    url(r"^$", views.blog_index),



# http://127.0.0.2:8080/blog/user/new_user/  =>blog_user_signup
    url(r"^user/new_user/$", views.new_user,name="blog_user_signup"),

# http://127.0.0.2:8080/blog/user/login/ =>blog_user_login
    url(r"^user/login/$", views.user_login,name="blog_user_login"),




# http://127.0.0.2:8080/blog/user/form/login/
    url(r"^user/form/login/$", views.user_form_login),



# http://127.0.0.2:8080/blog/user_register/
    url(r"^user_register/$", views.user_register),


# http://127.0.0.2:8080/blog/user_register/
    url(r"^bootstrap/$", views.bootstrap),


# http://127.0.0.2:8080/blog/student-list/
    url(r"^student-list/$", views.student_list),





]

mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

# http://127.0.0.2:8080/
    url(r"^$",views.index,name='home'),

# http://127.0.0.2:8080/
    url(r"^",include("myuser.urls")),


# http://127.0.0.2:8080/home/
    url(r"^home/$",views.home),

# http://127.0.0.2:8080/blog/ => mywebsite_blog
    url(r"^blogs/", include('blog.urls',namespace="blog"),name="mywebsite_blog"),
    # url(r"^blog/$", include('blog.urls'))

# http://127.0.0.2:8080/movies/
    url(r"^movies/", include('movie.urls'))
    # url(r"^blog/$", include('blog.urls'))
]



# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# Create your models here.
class StudentPortal(models.Model):
    user_name=models.CharField(max_length=25)
    user_email=models.EmailField()
    user_pass=models.CharField(max_length=15)

    def __str__(self):
        return self.user_email

class EmployeeDetails(models.Model):
    emp_name=models.CharField(max_length=25)
    emp_user=models.CharField(max_length=8)
    emp_email=models.EmailField()
    emp_pass=models.CharField(max_length=15)
    emp_address=models.TextField()

    def __str__(self):
        return self.emp_name+" - "+self.emp_user

blog/forms.py
from django import forms


class StudentPortalLoginForm(forms.Form):
    uname=forms.CharField(label="User id:",max_length=15)
    uemail=forms.EmailField(label="User Email:")
    pword=forms.CharField(label="Password:",widget=forms.PasswordInput())

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect

# from .models import StudentPortal
from . import models
from . import forms



# Create your views here.
def blog_index(request):
    # return HttpResponse("<h1>This blog page</h1>")
    return render(request, 'home/index.html')


def new_user(request):
    return render(request, 'user_form/user_registration.html')

def user_form_login(request):
    st_form=forms.StudentPortalLoginForm()
    context={
        "st_form":st_form
    }
    return render(request,'user_form/user_form_login.html',
                  context)

def user_login(request):
    if request.method=='GET':
        if 'username' in request.session:
            request.session['username']
            # username=request.session['username']
            # print("Session user name:",username)
            return redirect('/home/')
        return render(request, 'user_form/user_login.html')

    if request.method == 'POST':
        uname = request.POST['username']
        pword = request.POST['password']

        u_object = models.StudentPortal.objects.filter(user_email=uname)

        if len(u_object)< 1 or pword != u_object[0].user_pass:

            # return HttpResponseRedirect('/blog/user/login/')
            return redirect('/blogs/user/login/',msg="User id or Password is wrong")

        # if pword!=u_object[0].user_pass:
        #     return HttpResponseRedirect('/blog/user/login/')

        # print("User credentials: \n"
        #       "User name:",uname,"\n",
        #       "User password:",pword)
        request.session['username']=uname

        return HttpResponseRedirect('/home/')


def user_register(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        psw = request.POST['psw']
        print("Name:", name, "Email:", email, "Pass:", psw)

        st_obj = models.StudentPortal()
        st_obj.user_name = name
        st_obj.user_email = email
        st_obj.user_pass = psw
        st_obj.save()

    return HttpResponse("<h1>Data saved.</h1>")


def bootstrap(request):
    return render(request, 'home/home.html')


def student_list(request):
    st_list = models.StudentPortal.objects.all()
    context = {
        "student_list": st_list
    }
    return render(request, 'user_form/student_list.html', context={"key": "Student List", "student_list": st_list}
                  )

blog/templates/user_form/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
<h1>{{key}}</h1>
<ol>
    {% for st in student_list %}
    <li>
        <ul style="background-color:lightblue;margin-top:20px;margin-bottom:20px">
            <li>{{st.user_name}}</li>
            <li>{{st.user_pass}}</li>
            <li>{{st.user_email}}</li>
        </ul>
    </li>
    {% endfor %}
</ol>
</body>
</html>

blog/templates/user_form/user_form_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="#">
    {% csrf_token %}
    {{st_form.as_ul}}
    <input type="submit" name="Register">
</form>
</body>
</html>

blog/templates/user_form/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <title>Student Login</title>
</head>
<body>
<div class="container">
    <form action="{% url 'blog:blog_user_login' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <h2 style="text-align:center">Login with Social Media or Manually</h2>
            <div class="vl">
                <span class="vl-innertext">or</span>
            </div>

            <div class="col">
                <a href="#" class="fb btn">
                    <i class="fa fa-facebook fa-fw"></i> Login with Facebook
                </a>
                <a href="#" class="twitter btn">
                    <i class="fa fa-twitter fa-fw"></i> Login with Twitter
                </a>
                <a href="#" class="google btn"><i class="fa fa-google fa-fw">
                </i> Login with Google+
                </a>
            </div>

            <div class="col">
                <div class="hide-md-lg">
                    <p>Or sign in manually:</p>
                </div>

                <input type="text" name="username" placeholder="Username" required>
                <input type="password" name="password" placeholder="Password" required>
                <input type="submit" value="Login">
            </div>

        </div>
    </form>
</div>

<div class="bottom-container">
    <div class="row">
        <div class="col">
            <!--<a href="/blog/user/new_user/" style="color:white" class="btn">Sign up</a>-->
            <a href="{% url 'blog:blog_user_signup' %}" style="color:white" class="btn">Sign up</a>
        </div>
        <div class="col">
            <a href="#" style="color:white" class="btn">Forgot password?</a>
        </div>
    </div>
</div>

</body>
</html>

blog/templates/user_form/user_registration.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'user_form/styles.css' %}">
</head>
<body>

<form action="/blog/user_register/" method="post" style="background-color:white">
    {% csrf_token %}
    <div>
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>

        <label for="name_id"><b>Name</b></label>
        <input type="text" id="name_id" placeholder="Enter Name" name="name" required>

        <label for="email_id"><b>Email</b></label>
        <input type="text" id="email_id" placeholder="Enter Email" name="email" required>

        <label for="psw_id"><b>Password</b></label>
        <input type="password" id="psw_id" placeholder="Enter Password" name="psw" required>

        <hr>
        <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

        <button type="submit" class="registerbtn">Register</button>
    </div>

    <div>
        <!--<p>Already have an account? <a href="/blog/user/login/">Sign in</a>.</p>-->
        <p>Already have an account? <a href="{% url 'blog:blog_user_login' %}">Sign in</a>.</p>
    </div>
</form>

</body>
</html>